version: '3'

services:
  mock_app:
    build: .
    ports:
      - "12345:12345"
    volumes:
      - .:/app
    environment:
      DEBUG: 'true'
    command:
      - "uvicorn"
      - "app.app:app"
      - "--reload"
      - "--workers"
      - "1"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "12345"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.5'
          memory: 50M

  celery_worker:
    restart: always
    build: .
    volumes:
      - .:/app
    command:
      - "celery"
      - "-A"
      - "app.worker.celery_app"
      - "worker"
      - "--loglevel=INFO"
    depends_on:
      - rabbitmq
      - redis
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 100M
        reservations:
          cpus: '0.50'
          memory: 50M

  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - "5672:5672"    # expose amqp port
      - "15672:15672"  # expose management port
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=Pass1234
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 200M
        reservations:
          cpus: '0.50'
          memory: 100M

  redis:
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.50'
          memory: 50M

  flower:
    image: mher/flower:2.0
    build: .
    command:
      - "celery"
      - "-A"
      - "app.worker.celery_app"
      - "flower"
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=pyamqp://user:Pass1234@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - FLOWER_UNAUTHENTICATED_API=true
    depends_on:
      - celery_worker
